<?php require_once(dirname(__FILE__) . "/../app/escpos/Escpos.php");
							$printer = new Escpos();
							$printer -> feed();
							$printer -> feed();
							$printer -> setJustification(Escpos::JUSTIFY_CENTER);
							$printer -> selectPrintMode(Escpos::MODE_DOUBLE_WIDTH);
						    $printer -> text("Cocina\n");
						    $printer -> selectPrintMode();
							$printer -> setJustification(Escpos::JUSTIFY_LEFT);
						    $printer -> text("Fecha: 09-11-2015 / Hora: 16:25:09\n");
						    $printer -> text("Mesa:  Mesa 05\n");
						    $printer -> text("Mozo:  ivanG\n");
						    $printer -> text("------------------------------------------------\n");
						    $printer -> text("Cant.      Descripción\n");
						    $printer -> text("------------------------------------------------\n");$printer -> text("X1   Humita\n");$printer -> text("X1   Salchipapas Especial\n");$printer -> text("------------------------------------------------\n");$printer -> cut();$printer -> close();