<?php require_once(dirname(__FILE__) . "/../app/escpos/Escpos.php");
							$printer = new Escpos();
							$printer -> feed();
							$printer -> feed();
							$printer -> setJustification(Escpos::JUSTIFY_CENTER);
							$printer -> selectPrintMode(Escpos::MODE_DOUBLE_WIDTH);
						    $printer -> text("Pasteleria\n");
						    $printer -> selectPrintMode();
							$printer -> setJustification(Escpos::JUSTIFY_LEFT);
						    $printer -> text("Fecha: 13-07-2015 / Hora: 16:18:53\n");
						    $printer -> text("Mesa:  Mesa 14\n");
						    $printer -> text("Mozo:  cristopherq\n");
						    $printer -> text("------------------------------------------------\n");
						    $printer -> text("Cant.      Descripción\n");
						    $printer -> text("------------------------------------------------\n");$printer -> text("X2   Pastel de Choclo porción\n");$printer -> text("------------------------------------------------\n");$printer -> cut();$printer -> close();